project:
  type: website
  output-dir: _site

website:
  title: "The Little Book of Calculus"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: en/index.qmd
        text: English
      - href: de/index.qmd
        text: Deutsch
      - href: es/index.qmd
        text: Español
      - href: vi/index.qmd
        text: Tiếng Việt
      - href: zh/index.qmd
        text: 中文
      - href: ja/index.qmd
        text: 日本語

format:
  html:
    theme: cosmo
    toc: true
