project:
  type: website
  output-dir: _site

website:
  title: "The Little Book of Calculus"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: en/index.qmd
        text: English
      - href: pt/index.qmd
        text: Português
      - href: de/index.qmd
        text: Deutsch
      - href: es/index.qmd
        text: Español
      - href: fr/index.qmd
        text: Français
      - href: it/index.qmd
        text: Italiano
      - href: vi/index.qmd
        text: Tiếng Việt
      - href: zh/index.qmd
        text: 中文
      - href: ja/index.qmd
        text: 日本語
      - href: ko/index.qmd
        text: 한국어
      - href: ar/index.qmd
        text: العربية
      - href: ru/index.qmd
        text: Русский
      - href: hi/index.qmd
        text: हिन्दी
      - href: sa/index.qmd
        text: संस्कृतम्
      - href: pi/index.qmd
        text: Pāḷi
      - href: bo/index.qmd
        text: བོད་ཡིག

format:
  html:
    theme: cosmo
    toc: true
